config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  resources :users, only: [:show, :new, :create]
  resources :restaurants do
    resources :reservations, only: [:show, :create, :destroy]
    resources :cuisines, only: [:index, :show, :new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_and_belongs_to_many :restaurants

  def index
    @cuisines = Cuisine.find.all
  end

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)

    if @cuisine.save
      flash[:notice] = "You created a new type of cuisine."
      redirect_to cuisines_url
    else
      flash[:alert] = "Woops. Looks like that didn't save."
      render :new
    end
  end

  private
  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates :user, presence: true
  validates :time, presence: true
  validates :party_size, presence: true, numericality: true

  validate :time_cannot_be_in_the_past
  validate :restaurant_over_capacity?

  before_validation :convert_time_to_utc, on: [:create, :update]

  def convert_time_to_utc
    timezone = Time.now.zone
    self.time -= Time.zone_offset(timezone)
  end

  private
  def time_cannot_be_in_the_past
    if time && time < Time.now.utc
      errors.add(:time, "cannot be in the past.")
    end
  end

  def restaurant_over_capacity?
    if !restaurant.available?(party_size, time)
      errors.add(:base, 'the restaurant does not have sufficient capacity')
    end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  has_and_belongs_to_many :cuisines
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :capacity, presence: true, numericality: true
  validates :address, presence: true, uniqueness: true

  def available?(size, time)
    r = reservations.where(time: time)
    capacity > size + r.sum(:party_size)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

  has_many :reservations
  has_many :restaurants, through: :reservations
  has_many :businesses, class_name: "Restaurant", foreign_key: "owner_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  private
  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.restaurant = @restaurant

    if @reservation.save
      flash[:notice] = "Reservation booked at #{@restaurant.name}"
      redirect_to restaurants_path
    else
      flash[:alert] = "Woops, your reservation wasn't saved!"
      render "/restaurants/show"
    end
  end

  def show
  end

  def destroy
  end

  private
  def reservation_params
    params.require(:reservation).permit(:party_size, :time)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_user

    if @restaurant.save
      flash[:notice] = "You are now the proud owner of #{@restaurant.name}!"
      redirect_to restaurants_url
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = @restaurant.reservations.build
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update_attributes(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant #{@restaurant.name} has been updated."
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = "Unable to update #{@restaurant.name}."
      render :edit
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :address,
      :capacity,
      :timezone,
      :type_of_cuisine)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      flash[:notice] = "Successfully logged in!"
      session[:user_id] = user.id
      redirect_to :root
    else
      flash[:alert] = "Wrong email address or password.  Try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out."
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "YOU CREATED AN ACCOUNT! NICE!"
      redirect_to :root
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <p>
    Logged in as <%= current_user.name %>.
    <%= link_to 'Log out', session_path(:current), method: :delete %> |
    <%= link_to 'Make a Reservation', restaurants_path %> |
    <%= link_to 'My Reservations', user_path(current_user) %>
  </p>
<% else %>
  <p>
    <%= link_to 'Create an account', new_user_path %>
    <%= link_to 'Log in', new_session_path  %>
  </p>
<% end %>

<%= yield %>

</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/restaurants/_reservation_form.html.erb
<h2>Reserve a table at <span class="name"><%= @restaurant.name %></span></h2>

<%= form_for [@restaurant, @reservation] do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_messages">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="field">
    <%= f.label :time %>
    <%= f.datetime_select :time,
          discard_minute: true,
          discard_second: true,
          ampm: true,
          default: Time.now + 1.hour %>
  </p>
  <p class="field">
    <%= f.label :party_size %>
    <%= f.number_field :party_size %>
  </p>
  <p class="submit">
    <%= f.button 'Reserve a table' %>
  </p>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Update restaurant: <%= @restaurant.name %></h1>

<% if @restaurant.errors.any? %>
  <div id="errors">
    <h2>
      <%= pluralize(@restaurant.errors.count, "error") %> prohibited your restaurant from being saved:
    </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @restaurant do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="button">
    <%= f.button %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1>All ze restaurants!</h1>

<% if current_user %>
  <%= link_to "Create Restaurant", new_restaurant_path %>
<% else %>
  <p><%= "Know a cool restaurant? Sign up to share it with the world!" %> <%= link_to 'Sign Up', new_user_path %>
  </p>
<% end %>

<% if @restaurants.any? %>

  <ul>
    <% @restaurants.each do |r| %>
      <li><%= link_to r.name, restaurant_path(r) %></li>
    <% end %>
  </ul>

<% end %>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_messages">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited your restaurant from being saved:</h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="button">
    <%= f.button %>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<nav class="edit">
  <% if current_user == @restaurant.owner %>
    <%= link_to 'Edit restaurant information', edit_restaurant_path(@restaurant) %>
  <% end %>
</nav>

<p>
  <strong>Owner:</strong>
  <%= @restaurant.owner.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @restaurant.capacity %>
</p>

<%= render 'reservation_form' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
    <div id="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited your account from being created:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="button">
    <%= f.button %>
  </div>


<% end %>

app/views/users/show.html.erb
<h1>Your Reservations</h1>

<% if @user.reservations.any? %>

  <ul>
    <% @user.reservations.each do |r| %>
      <li>
        <p> <%= link_to r.restaurant.name, restaurant_path(r.restaurant) %></p>
        <p><%= r.time.to_formatted_s(:long_ordinal)  %></p>
      </li>
    <% end %>
  </ul>

<% else %>
  <%= link_to 'Make a reservation', restaurants_path %>

<% end %>